            - name: pull-request merge
  # You may pin to the exact commit or the version.
  # uses: sudo-bot/action-pull-request-merge@5b58b5cb1e46bda23160c3a6d56beeec7036c7e2
  uses: sudo-bot/action-pull-request-merge@v1.2.0
  with:
    # GitHub Token
    github-token: 
    # Pull Request number
    number: 
    # The merge method: merge,squash,rebase,fast-forward
    merge-method: # optional, default is merge
    # The allowed usernames in javascript regex format
    allowed-usernames-regex: # optional, default is ^.*$
    # The label that will trigger the merge, (empty or absent to disable the check)
    filter-label: # optional, default is 
    # The merge title
    merge-title: # optional, default is 
    # The merge message
    merge-message: # optional, default is 
          
