name: PR auto-merge (sudo-bot)

on:
  workflow_dispatch:
  pull_request:
    types: [labeled, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: pull-request merge
        uses: sudo-bot/action-pull-request-merge@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          merge-method: merge
          filter-label: automerge
